### ISSUE TITLE
Issue: Background Gradient Not Displayed Correctly on Initial Page Load for Light Mode Users

### ISSUE THREAD

**Issue by jerryluo11** [adeshkumar1/personal-website#1]
**Description:**
When users have their device or browser set to light mode, the background gradient on our webpage fails to display correctly upon the initial page load. Instead of showing the intended gradient, users are either presented with a solid color or an incorrect gradient. The issue seems to resolve itself after a page refresh or navigating to a different page and then returning.

**Steps to Reproduce:**
Set your device or browser to light mode.
Open the webpage.
Observe the background gradient.
Expected Behavior:
The background gradient should display correctly on the initial page load without requiring any user intervention.

**Actual Behavior:**
The background gradient does not display as intended on the initial page load. It shows either a solid color or an incorrect gradient.

**Comment by adeshkumar1** [comment]
Hey jerry, thanks for pointing this issue out, I think I have fixed the issue, please check out the website again and LMK. Thanks!
